### PR TITLE
2.0.2

### PR DESCRIPTION
**Pull request by jasongrout**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jasongrout** [comment]
@conda-forge-admin, please rerender

**Comment by jasongrout** [comment]
@conda-forge-admin, please rerender

**Comment by jasongrout** [comment]
@saulshanabrook - I added you to the maintainers as well.

**Comment by saulshanabrook** [comment]
Thank you Jason! So it looks like if we do two release, you just have to do one after another?

So if we do a 1 patch release, do we just update this to be that 1.x version?

**Comment by jasongrout** [comment]
No, we should have a separate branch for each release line, I think. I took a shortcut here by doing the patch release then the minor. If we have another 2.0.3, I think we should make a 2.0.x branch here.

**Comment by saulshanabrook** [comment]
Ah I see, good to know!

**Comment by saulshanabrook** [comment]
I didn't know conda forge builds on all the branches.

**Comment by jasongrout** [comment]
Yes, that's why they don't want prs from branches here, only from forks.

**Comment by saulshanabrook** [comment]
@jasongrout Ah good point! Thanks.

**Pull request merged**
