### PR TITLE
JupyterLab 3.0.0rc13

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Hooray more rc!
- https://github.com/jupyterlab/jupyterlab/issues/9295
- https://github.com/jupyterlab/extension-examples/pull/130

### CODE REVIEW

**Comment by bollwyvl** [comment]
I'll note I am seeing some clobber warnings:
```
Verifying transaction: ...working... 
ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/linux-64::jupyter_server-1.0.8-py37h89c1867_0, conda-forge/linux-64::notebook-6.1.5-py37h89c1867_0
  path: 'bin/jupyter-bundlerextension'


ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/linux-64::jupyter_server-1.0.8-py37h89c1867_0, conda-forge/noarch::nbclassic-0.2.3-py_0
  path: 'lib/python3.7/site-packages/tests/__init__.py'


ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/linux-64::jupyter_server-1.0.8-py37h89c1867_0, conda-forge/noarch::nbclassic-0.2.3-py_0
  path: 'lib/python3.7/site-packages/tests/__pycache__/__init__.cpython-37.pyc'


ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/linux-64::jupyter_server-1.0.8-py37h89c1867_0, conda-forge/noarch::nbclassic-0.2.3-py_0
  path: 'lib/python3.7/site-packages/tests/__pycache__/conftest.cpython-37.pyc'


ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/linux-64::jupyter_server-1.0.8-py37h89c1867_0, conda-forge/noarch::nbclassic-0.2.3-py_0
  path: 'lib/python3.7/site-packages/tests/conftest.py'
```

`site-packages/tests` is kind of a dumping ground, but this does point to potentially dropping them from the distribution, especially since the tests aren't even executed, and probably wouldn't work anyway.

**Comment by jtpio** [comment]
Thanks for pointing that out!

Should we merge this PR anyway and address the warnings separately?

**Comment by jasongrout** [comment]
@bollwyvl - are these warnings new in rc13? It sounds like they've been around for a while?

**Comment by bollwyvl** [comment]
No, I'm sure they aren't new... same kinda thing as the `pytest11` `entry_point`: I was just hadn't watched the full build (cuz who doesn't like some nice log messages? it's like the post-modern campfire...) before or tried to build a `constructor` yet with lab 3 (oh man, am I itching to, though), which is one of the tools that would fail/complain. But there aren't a ton of reasons to install `server` and `classic` yet, so the support issues will only show up when lab starts pushing.

**Comment by jasongrout** [comment]
Thanks. Let's merge this to get rc13 out so people can use it, and fix these issues in another rc (since it kind of sounds like they should be fixed in the original packaging anyway).

**Comment by bollwyvl** [comment]
> fixed in the original packaging anyway).

You bet! I think they [both](https://github.com/jupyter-server/jupyter_server/blob/1.0.x/setup.py#L18) [have](https://github.com/jupyterlab/nbclassic/blob/master/setup.py#L35).

Though we can still go to `noarch` on `jupyter_server`...

https://github.com/conda-forge/jupyter_server-feedstock/pull/26

**Pull request merged**
