### PR TITLE
BLD: meta.yml: add nodejs>=10 as a run requirement

### LINKED ISSUE #233: Depend upon nodejs so that jupyterlab works out of the box
Issue:

jupyterlab-feedstock should depend upon `-c conda-forge nodejs` so that running `jupyter lab build` with `-c conda-forge jupyterlab` just works ouf of the box.

Is `nodejs` an optional dependency? Sort of.

Should it be possible to just install extensions without having to figure out that you need to also install `nodejs`? Yes.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

### PR DESCRIPTION
**Pull request by westurner**
fixes #233

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by westurner** [comment]
I hope to have more time for this hopefully later this week.

**Comment by hoechenberger** [comment]
Hello @westurner, what's the status of this one? :)

**Comment by westurner** [comment]
I think this is ready to merge

**Comment by jasongrout** [comment]
Let's discuss this in our dev meeting on Wednesday.

JupyterLab itself, as a base package, does not depend on nodejs, so not having nodejs as a dependency was an explicit decision early on.

Installing extensions in JupyterLab 2 does require nodejs, but unfortunately conda does not have the concept of optional dependencies. So there is a decision of picking up a heavy dependency for a common usecase, or keeping the dependencies down for also a common usecase.

In JupyterLab 3, due out very soon, the extension system does not require nodejs, so the problem will go away soon as extensions migrate to the new system.

**Comment by jasongrout** [comment]
> In JupyterLab 3, due out very soon, the extension system does not require nodejs, so the problem will go away soon as extensions migrate to the new system. So this is a question of timing as well as tradeoffs.

Update: JupyterLab 3 is out now.

**Comment by westurner** [comment]
Is node necessary to build JupyterLab extensions; just not for end users?

**Comment by jasongrout** [comment]
> Is node necessary to build JupyterLab extensions; just not for end users?

Node is still necessary to develop jlab extensions, and to install "source extensions", but is not needed to install and use "prebuilt extensions", the new kind of extension introduced in jlab 3. We expect most extensions to move to prebuilt extensions over the coming months as they migrate to jlab 3.

**Comment by westurner** [comment]
https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html#prebuilt-extensions

https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html#developing-a-prebuilt-extension

https://github.com/jupyterlab/extension-cookiecutter-ts :

> A cookiecutter recipe for JupyterLab extensions in Typescript

https://github.com/jupyterlab/extension-cookiecutter-js :

> A cookiecutter template for creating a JupyterLab extension in CommonJS JavaScript.

> *

**Comment by jasongrout** [comment]
This is also a good overview of extensions, including prebuilt extensions: https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html#overview-of-extensions

**Pull request closed without merging**
