### PR TITLE
Bump to 3.6.4

### PR DESCRIPTION
**Pull request by fcollonval**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* ~~Bumped the build number (if the version is unchanged)~~
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Notes:
- [x] blocked by https://github.com/conda-forge/jupyter_ydoc-feedstock/pull/35

### CODE REVIEW

**Comment by fcollonval** [comment]
@conda-forge-admin, please rerender

**Comment by fcollonval** [comment]
Thanks a lot @bollwyvl 

I open https://github.com/conda-forge/jupyter_ydoc-feedstock/pull/34 to publish the missing dep

**Comment by fcollonval** [comment]
🤣 ok you were already on it so closing mine PR - sorry for that.

**Comment by bollwyvl** [comment]
Too late now, but there have so many releases in the 0.3.x line... are we quite sure the seldom-useful-in-python `~` is correct for this pin?

**Pull request merged**
