### PR TITLE
Update to jupyterlab_server >= 1.1.0

### PR DESCRIPTION
**Pull request by jtpio**
Align the dependencies with the ones listed in JupyterLab `setup.py`:

https://github.com/jupyterlab/jupyterlab/blob/2619a79d89f97441d078b98a719da4a9bfccbcb6/setup.py#L139-L144

This should fix: https://github.com/jupyterlab/jupyterlab/issues/8231

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by saulshanabrook** [comment]
@jtpio I believe we should bump the build number since the version is the same?

**Comment by jtpio** [comment]
Ah indeed, good catch!

**Comment by saulshanabrook** [comment]
@conda-forge-admin, please rerender

**Comment by blink1073** [comment]
Thanks!

**Pull request merged**
