### PR TITLE
Release 0.19.0

### PR DESCRIPTION
**Pull request by dhirschfeld**
Is this all that's required to release the latest version? If so, that's pretty slick!

### CODE REVIEW

**Comment by jakirkham** [comment]
As long as there are no dependency changes, yeah that's it.

**Comment by dhirschfeld** [comment]
I did check the `setup.py` and it didn't look like there had been any dependency changes so hopefully we're good to go!

**Comment by dhirschfeld** [comment]
@blink1073 - if you've got time to pull the trigger on this it would be great to have conda packages for the latest & greatest :)

**Comment by blink1073** [comment]
Thanks, @dhirschfeld, I completely forgot this time!

**Pull request merged**
