### PR TITLE
jupyterlab 4.2.4

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
Currently seeing some outages, will check back in a few hours.

**Comment by jakirkham** [comment]
Yep CI is not running. Please see linked issue for details

xref: https://github.com/conda-forge/status/issues/184

**Comment by jakirkham** [comment]
@conda-forge-admin please restart CI

**Comment by jakirkham** [comment]
Looks like CI is back

**Pull request merged**
