### PR TITLE
[bot-experiment] Add bot PRs for all current branches, cache azure artifacts

### PR DESCRIPTION
**Pull request by bollwyvl**
- maybe helps #173

This PR (once merged) should cause the bot to make PRs for branches:
- `2.x`
- `rc`
- `rc-2.x`

It will also upload the azure artifacts (but only on this branch) so they can be downloaded (from azure) if that is desirable. We could add that to the other branches as they have stuff, but not worth building right now

If this makes too many PRs, we can scale it back.

Not sure how it will play out, but would remove some manual processes.

### CODE REVIEW

**Comment by jasongrout** [comment]
Wait, what?! This is a thing! Awesome!

**Review by blink1073 — APPROVED** [review]
Cool!

**Comment by jasongrout** [comment]
Just curious: is this documented somewhere? Is this an intended use of abi_migration_branches?

**Comment by blink1073** [comment]
Here's what I found: https://conda-forge.org/docs/maintainer/conda_forge_yml.html

**Comment by blink1073** [comment]
Hahaha Jason, we're talking right past each other this morning.

**Comment by bollwyvl** [comment]
sry, should have included the link, save you guys some time. at least y'all did it in parallel. Let's punch it, and see what breaks.

**Comment by jasongrout** [comment]
I asked at https://gitter.im/conda-forge/regro-cf-autotick-bot?at=605dfbfe33346c16277a7182

**Comment by jasongrout** [comment]
https://gitter.im/conda-forge/regro-cf-autotick-bot?at=605dfcf48478e061b960a510 indicates this PR won't have the desired effect.

Code for the bot is at https://github.com/regro/cf-scripts

**Pull request merged**
