### PR TITLE
0.15.1

### PR DESCRIPTION
**Pull request by jasongrout**

### CODE REVIEW

**Comment by blink1073** [comment]
Thanks for catching this!

**Comment by jakirkham** [comment]
Please remember to fork and make changes from your fork, @jasongrout. As it is these builds will deploy before this PR is merged as it is a branch on the main feedstock and not a fork.

**Comment by jasongrout** [comment]
> Please remember to fork and make changes from your fork, @jasongrout. As it is these builds will deploy before this PR is merged as it is a branch on the main feedstock and not a fork.

Ah, thanks, sorry. I used github to edit the file and make a patch. I'm used to that making a branch in my fork, but I guess since I have write privileges here, it made a branch in this repo.

**Comment by jasongrout** [comment]
> Please remember to fork and make changes from your fork, @jasongrout. As it is these builds will deploy before this PR is merged as it is a branch on the main feedstock and not a fork.

Ah, thanks. I used github to edit the file and make a patch. I'm used to that making a branch in my fork, but I guess since I have write privileges here, it made a branch in this repo.

**Comment by jakirkham** [comment]
So if you want to edit on GitHub start by making the changes on your fork. Should also note GitHub will try to open a PR against your own fork and they don't make it easy to change. 😒 To fix this you have to navigate back to the main feedstock and open a PR there.

I've been meaning to drop GitHub a note on this workflow, but haven't had time. Though if someone wants to write one, I'd be happy to review and +1 a request to improve this workflow.

**Comment by jasongrout** [comment]
@blink1073 - what do you say we merge this (since the builds are going up anyway), and cut a 0.16.0 PR too?

**Comment by jasongrout** [comment]
And as usual, I'm behind you :)

**Comment by blink1073** [comment]
The 0.16.0 is done and merged, causing a conflict with this one.  I think we just need to leave this open and let the Travis build finish.

**Comment by jasongrout** [comment]
> The 0.16.0 is done and merged, causing a conflict with this one. I think we just need to leave this open and let the Travis build finish.

Yep, agreed.

**Comment by jasongrout** [comment]
Closing, since apparently all builds have been uploaded and this has been superseded.

**Comment by jakirkham** [comment]
So one could merge this into `master` in such a way that `master` doesn't change. That would keep the history intact in `git`. If you are unsure of how to do this, I'd be willing to help.

**Comment by jakirkham** [comment]
Sorry, wrong button. 😳

**Comment by jasongrout** [comment]
> So one could merge this into master in such a way that master doesn't change. That would keep the history intact in git. If you are unsure of how to do this, I'd be willing to help.

I'm happy to do so if you tell me what you're thinking. Merge and accept the current master as the winner of the conflict? I'm not sure exactly what sorts of things will trigger the bots.

**Comment by jakirkham** [comment]
> Merge and accept the current master as the winner of the conflict?

Exactly. In fact, `master` will win the whole diff. Please see PR ( https://github.com/conda-forge/jupyterlab-feedstock/pull/35 ).

**Comment by jakirkham** [comment]
Mainly am thinking this so that we can cleanup `jasongrout-patch-1` without losing the history. The reason being bots will try to re-render `jasongrout-patch-1` if it stays, but deleting without merging it somehow results in a loss of history.

**Pull request closed without merging**
