### PR TITLE
Bump to 0.5 and ensure emails are always sent

### PR DESCRIPTION
**Pull request by blink1073**

### CODE REVIEW

**Comment by jakirkham** [comment]
Please re-render with `conda-smithy` version `1.3.2`. Also changes to files like the `.travis.yml` will be overwritten in this process so you may need to tweak them after. Though if this is a feature you really want please open an issue over at the [conda-smithy repo]( https://github.com/conda-forge/conda-smithy ).

**Comment by jakirkham** [comment]
Please [re-render]( https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock ) with `conda-smithy` version `1.3.2`. Also changes to files like the `.travis.yml` will be overwritten in this process so you may need to tweak them after. Though if this is a feature you really want please open an issue over at the [conda-smithy repo]( https://github.com/conda-forge/conda-smithy ).

**Comment by jasongrout** [comment]
Thanks! I just advertised to lots of people that they can install from conda-forge :).

**Comment by bollwyvl** [comment]
Looks like the network devils prevented a number of the builds from getting uploaded... only seeing osx/win 3.4 versions... mauybe just needs a re-kick? or will be handled by #14...
https://anaconda.org/conda-forge/jupyterlab/files?version=0.5.0

**Comment by blink1073** [comment]
Yep, looks like merging #14 did the trick, that list is fully populated.

**Pull request merged**
