### PR TITLE
Release 0.28.3

### LINKED ISSUE #70: Include license file
Would be good to have the license file in the package using the [`license_file` metadata]( https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#license-file ).

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #70.

### CODE REVIEW

**Comment by jakirkham** [comment]
Could you please add `license_file: LICENSE` to `about` as well? Then we can close out issue ( https://github.com/conda-forge/jupyterlab-feedstock/issues/70 ).

**Comment by blink1073** [comment]
👍

**Comment by jakirkham** [comment]
Thanks!

**Comment by jakirkham** [comment]
Should the PR be renamed?

**Comment by blink1073** [comment]
Yep.

**Pull request merged**
