### PR TITLE
Release 0.20.0

### PR DESCRIPTION
**Pull request by dhirschfeld**
Ping @blink1073!

### CODE REVIEW

**Comment by dhirschfeld** [comment]
For ref CircleCI appeared to fail with the below error in the build:
```python-traceback
INFO conda_build.build:bundle_conda(865): Packaging jupyterlab-0.20.0-py27_0
compiling .pyc files...
  File "lib/python2.7/site-packages/jupyterlab/labextensions.py", line 84
    [print(ext) for ext in list_extensions(self.config_dir)]
         ^
SyntaxError: invalid syntax
```
...so it looks like it's missing a `from __future__ import print_function` for py27?

**Comment by dhirschfeld** [comment]
Though that can't be the only issue as the py35 build also fails with
```
Can't build C:\projects\jupyterlab-feedstock\recipe due to environment creation error:
Link error: Error: post-link failed for: local::jupyterlab-0.20.0-py35_0 
Command exited with code 1
```

**Comment by blink1073** [comment]
0.20.1 is out, but we are blocked on https://github.com/conda-forge/staged-recipes/pull/2852, which is a new dependency.

**Comment by dhirschfeld** [comment]
Ah, right - that would explain the other error. Since this is already closed there's nothing more to do here. I've added a +1 to the new staged recipe so will just wait for that to be merged and the next jlab released.

**Pull request closed without merging**
