### PR TITLE
Release 0.35 and switch to noarch

### PR DESCRIPTION
**Pull request by blink1073**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by blink1073** [comment]
I love me some noarch!

**Comment by jasongrout** [comment]
@blink1073, I thought we had decided to *not* switch to noarch yet, but instead delete the unlink scripts only in this version. See #111

**Comment by jasongrout** [comment]
(closing so we don't merge accidentally while we have the discussion...)

**Comment by jasongrout** [comment]
I put in #144 which follows the migration plan.

**Pull request closed without merging**
